packages:
  - "apps/**/*"
  - "packages/*"
  - "packages/business/bounded-contexts/*"
  - "packages/business/orchestrations/*"
  - "packages/business/*"
  - "packages/infrastructure/*"
  - "packages/shared/*"
