#!/usr/bin/env tsx
/**
 * This script embeds all static files from admin-panel/dist into a TypeScript module.
 * The embedded files can then be served directly from memory, making the app self-contained.
 *
 * Run this before building the fastify-api release to embed the React app.
 */

import { readdirSync, readFileSync, writeFileSync, statSync, existsSync } from "fs";
import { join, relative, dirname } from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const DIST_PATH = join(__dirname, "../../admin-panel/dist");
const OUTPUT_PATH = join(__dirname, "../src/services/admin-panel/embedded-files.ts");

function getMimeType(file: string): string {
  const ext = file.split(".").pop()?.toLowerCase();
  const mimes: Record<string, string> = {
    html: "text/html; charset=utf-8",
    css: "text/css; charset=utf-8",
    js: "application/javascript; charset=utf-8",
    mjs: "application/javascript; charset=utf-8",
    json: "application/json; charset=utf-8",
    svg: "image/svg+xml",
    png: "image/png",
    jpg: "image/jpeg",
    jpeg: "image/jpeg",
    gif: "image/gif",
    ico: "image/x-icon",
    webp: "image/webp",
    woff: "font/woff",
    woff2: "font/woff2",
    ttf: "font/ttf",
    eot: "application/vnd.ms-fontobject",
    otf: "font/otf",
    txt: "text/plain; charset=utf-8",
    xml: "application/xml",
    map: "application/json",
  };
  return mimes[ext || ""] || "application/octet-stream";
}

function isBinaryFile(mimeType: string): boolean {
  return (
    mimeType.startsWith("image/") ||
    mimeType.startsWith("font/") ||
    mimeType === "application/octet-stream" ||
    mimeType === "application/vnd.ms-fontobject"
  );
}

function walkDir(dir: string, files: string[] = []): string[] {
  for (const file of readdirSync(dir)) {
    const fullPath = join(dir, file);
    if (statSync(fullPath).isDirectory()) {
      walkDir(fullPath, files);
    } else {
      files.push(fullPath);
    }
  }
  return files;
}

function escapeString(str: string): string {
  return str
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\$/g, "\\$");
}

function main() {
  if (!existsSync(DIST_PATH)) {
    console.error(`❌ Admin panel dist not found at: ${DIST_PATH}`);
    console.error("   Run 'pnpm build' in apps/admin-panel first.");
    process.exit(1);
  }

  console.log(`📦 Embedding files from: ${DIST_PATH}`);

  const files = walkDir(DIST_PATH);

  let output = `// ═══════════════════════════════════════════════════════════════════════════════
// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by scripts/embed-admin-panel.ts
// Run 'pnpm embed:admin-panel' to regenerate
// ═══════════════════════════════════════════════════════════════════════════════

export interface EmbeddedFile {
  content: string | Buffer;
  type: string;
  binary: boolean;
}

export const EMBEDDED_FILES: Record<string, EmbeddedFile> = {
`;

  for (const file of files) {
    const relativePath = "/" + relative(DIST_PATH, file).replace(/\\/g, "/");
    const mimeType = getMimeType(file);
    const binary = isBinaryFile(mimeType);

    if (binary) {
      // Binary files: store as base64
      const content = readFileSync(file).toString("base64");
      output += `  "${relativePath}": {\n`;
      output += `    content: "${content}",\n`;
      output += `    type: "${mimeType}",\n`;
      output += `    binary: true,\n`;
      output += `  },\n`;
    } else {
      // Text files: store as escaped string
      const content = readFileSync(file, "utf-8");
      output += `  "${relativePath}": {\n`;
      output += `    content: \`${escapeString(content)}\`,\n`;
      output += `    type: "${mimeType}",\n`;
      output += `    binary: false,\n`;
      output += `  },\n`;
    }

    console.log(`  ✓ ${relativePath} (${mimeType})`);
  }

  output += `};

/**
 * Get an embedded file by path.
 * Returns the index.html for SPA fallback if path not found.
 */
export function getEmbeddedFile(path: string): EmbeddedFile | undefined {
  // Normalize path
  let normalizedPath = path.startsWith("/") ? path : "/" + path;

  // Try exact match
  if (EMBEDDED_FILES[normalizedPath]) {
    return EMBEDDED_FILES[normalizedPath];
  }

  // Try with /index.html suffix for directories
  if (!normalizedPath.includes(".")) {
    const indexPath = normalizedPath.endsWith("/")
      ? normalizedPath + "index.html"
      : normalizedPath + "/index.html";
    if (EMBEDDED_FILES[indexPath]) {
      return EMBEDDED_FILES[indexPath];
    }
  }

  return undefined;
}

/**
 * Get file content ready to be sent in response.
 * Handles base64 decoding for binary files.
 */
export function getFileContent(file: EmbeddedFile): string | Buffer {
  if (file.binary && typeof file.content === "string") {
    return Buffer.from(file.content, "base64");
  }
  return file.content;
}
`;

  writeFileSync(OUTPUT_PATH, output);

  console.log(`\n✅ Generated ${files.length} embedded files`);
  console.log(`📄 Output: ${OUTPUT_PATH}`);
}

main();

